---
title: "Monthly Payroll"
format: html
editor: visual
params:
  month: "15"
  year: "2024"
  payroll_folder_url: "https://drive.google.com/drive/folders/1si6xal0w6JPyy-m7RVm3zJ9q7n0tf2tm"
  google_user_email: "andymaffei@gmail.com"
  payrate_file_name: "tyc-payrates"
  payroll_csv_prefix: "tyc_wlpayroll"
  instructor_file_name: "tyc-instructors"
  payroll_csvs_folder_name: "payroll_csvs"
  instructor_pdfs_folder_name: "instructor_pdfs"
---

## TYC Monthly Payroll

This is a log of the monthly payroll run for The Yoga Collaborative.

## Initialize the payroll run

```{r}
#| echo: false
#| include: false
#| results: hide

# Load required libraries
library(tidyverse)
library(shiny)
library(quarto)
library(googledrive)
library(googlesheets4)
library(gt)

# Authorize google sheets access 
gs4_auth(email=params$google_user_email)

# Authenticate with Google Drive
drive_auth(email=params$google_user_email)

# Extract the ID from the URL
payroll_folder_id <- gsub(".*/folders/(.*)$", "\\1", 
                  params$payroll_folder_url)

# Get directory listing for the top level payroll folder
payroll_folder_dirlist <- drive_ls(path = 
                                     as_id(payroll_folder_id))

# Get payrate spreadsheet reference from dirlist
payrate_file <-  payroll_folder_dirlist |>
  filter(name == params$payrate_file_name)

# Get instructor spreadsheet reference from dirlist
instructor_file <- payroll_folder_dirlist |>
  filter(name == params$instructor_file_name)

# Get payroll folder reference from dirlist
payrollcsvs_folder <- payroll_folder_dirlist |>
  filter(name == params$payroll_csvs_folder_name)

# Get instructor pdf folder ref from dirlist
instructorpdf_folder <- payroll_folder_dirlist |>
  filter(name == params$instructor_pdfs_folder_name)

# Create local csv and pdf subdirectories
dir.create("csvs",showWarnings = FALSE)
dir.create("instructor_pdfs",showWarnings = FALSE)

```

## Payrate Table for this month

```{r}
#| echo: false
#| include: true

# Generate payrate table
payrate_tbl <- read_sheet(payrate_file$id) |>
  rename(
    hourly_pay_rate = `WL Hourly Payrate`,
    pp7 = PP7,
    cap = Cap,
    base0 = `Base 0`,
    base1 = `Base 1 Plus`)

# Display the table in the report
gt(payrate_tbl, rowname_col = "hourly_pay_rate") |>
   fmt_currency(columns = c(cap, base1, pp7, base0)) |>
   cols_label(hourly_pay_rate = "Hourly Pay Rate", 
              cap = "Cap", 
              base1 = "Base 1",
              pp7 = "PP7",
              base0 = "Base 0")
```

## Instructor Table for this Month

```{r}
#| echo: false
#| include: true

# Generate Instructor Table

instructor_tbl <- read_sheet(instructor_file$id) |>
  rename(
    name = Name,
    instructor_pay_rate = 'Hourly Pay Rate',
    anniversary_date = 'Anniversary Date'
  )

# Display the table in the report
gt(instructor_tbl) |>
   cols_label(name = "Name", 
              instructor_pay_rate = "Hourly Pay Rate",
              anniversary_date = "Anniversary Date")
```

## Read this months WL Payroll CSV file

```{r}
#| echo: false
#| include: true

# Get directory listing for the top level payroll folder
payrollcsvs_folder_dirlist <- drive_ls(path = 
                                     as_id(payrollcsvs_folder$id))

# Construct the folder and file names
payroll_file_name <- paste("tyc_wlpayroll-",
                           params$year,
                           params$month,".csv",
                           sep = "")

# Find the csv file
payrollcsv_file <-  payrollcsvs_folder_dirlist |>
  filter(name == payroll_file_name)

# Download the file
drive_download(payrollcsv_file$id, overwrite = TRUE)

# Read the file into a tibble
services_held <- read_csv(
  payroll_file_name,
  col_types = cols(
    s_staff.text_fullname = col_character(),
    Client = col_skip(),
    Email = col_skip(),
    Phone = col_skip(),
    `Member ID` = col_skip(),
    Day = col_character(),
    Time = col_character(),
    # Day = col_date(format = "%b %d, %Y"),
    # Time = col_time(format = "%I:%M%p"),
    `Service Name.` = col_character(),
    `Service Type` = col_character(),
    `Commission Sales` = col_skip(),
    Booked = col_integer(),
    Attended = col_integer(),
    `No shows` = col_skip(),
    `Late Cancels` = col_integer(),
    `Base Rate` = col_skip(),
    Bonus = col_skip(),
    Total = col_character(),
    `Tip Amount` = col_skip(),
    `Hourly Pay Rate` = col_character(),
  )
)
gt(services_held)
```
